version: "3.9"

services:
  samp-query-bot:
    image: ghcr.io/madeline-bot/selfhost:master
    env_file: .env
    volumes:
      - ./logs:/app/logs
    networks:
      - samp-query-bot-network
    restart:
      on-failure

networks:
  samp-query-bot-network:
